#a Copyright
#  
#  This file 'Makefile' copyright Gavin J Stark 2003, 2004
#  

#a Global variables
CYCLICITY := ${CYCLICITY_ROOT}
MODEL_LIST := model_list

#a Include standard build makefile
include ${CYCLICITY}/scripts/simulation_build_make

#a Editor preferences and notes
# Local Variables: ***
# mode: Makefile ***
# outline-regexp: "#[a!]\\\|#[\t ]*[b-z][\t ]" ***
# End: ***

