#!/usr/bin/perl

#a Copyright
#  
#  This file 'create_make' copyright Gavin J Stark 2003, 2004
#  

#a Main
die "Syntax: create_make <model_list> <makefile>\n" unless ($#ARGV==1);

$model_list = @ARGV[0];
$makefile = @ARGV[1];

#a Read the descriptor list
open( desc, $model_list );
$#tests = 0;
$#asms = 0;
$#ccs = 0;
while (<desc>)
{
    chomp;
    $line = $_;
    next if $line =~/^\s*#/;
    next if $line =~/^\s*;/;
    if ($line =~ /asm\s+(\S*)\s+(.*)/) {
        $dir = $1;
        $file = $2;
        $asms[$#asms] = "$dir $file";
        $#asms++;
    }
    if ($line =~ /cc\s+(\S*)\s+(.*)/) {
        $dir = $1;
        $file = $2;
        $ccs[$#ccs] = "$dir $file";
        $#ccs++;
    }
    if ($line =~ /test\s+(\S*)\s+(\S*)\s+(.*)/) {
        $type = $1;
        $test = $2;
        $options = $3;
        $objs = "";
        foreach $option (split(/ /,$options)) {
            if ($option =~ /(.*):(.*)/) {
                $objs .= "$1:$2@@@";
            }
        }
        $tests[$#tests] = "$test $type $objs";
        $#tests++;
    }
}
close( desc );
$#asms--;
$#ccs--;
$#tests--;

#a Output the models makefile
open( make, ">$makefile" );
print make  "TEST_BINARIES := \\\n";
foreach $i (@tests) {
    ($test, $type, $objs) = split(/ /,$i);
    print make  "    bin/$test.$type.mif \\\n";
    print make  "    bin/$test.$type.coe \\\n";
}
print make  " \n";

foreach $asm (@asms) {
    next if ($asm=~/^\s*$/);
    ($dir, $file) = split(/ /,$asm);
    print make "obj/$dir.$file.o: src/$dir/$file.S\n";
    print make "\t\${ARM_CC} \${ARM_CC_FLAGS} -c src/$dir/$file.S -o obj/$dir.$file.o\n";
    print make "\n";
}

foreach $cc (@ccs) {
    next if ($cc=~/^\s*$/);
    ($dir, $file) = split(/ /,$cc);
    print make "obj/$dir.$file.o: src/$dir/$file.c\n";
    print make "\t\${ARM_CC} \${ARM_CC_FLAGS} -c src/$dir/$file.c -o obj/$dir.$file.o\n";
    print make "\n";
}

foreach $i (@tests) {
    ($test, $type, $objs) = split(/ /,$i);

    print make "bin/$test.$type.bin: \\\n";
    foreach $obj (split(/@@@/,$objs)) {
        next if ($obj=~/^\s*$/);
        if ($obj=~/^([^:]*):(.*)/) {
            print make "\t\tobj/${1}.$2.o \\\n";
        }
    }
    print make "\t\tscripts/build.$type.script\n";
    print make "\t\${ARM_LD} -T scripts/build.$type.script --Map bin/$test.$type.map -o obj/$test.$type.elf \\\n";
    foreach $obj (split(/@@@/,$objs)) {
        next if ($obj=~/^\s*$/);
        if ($obj=~/^([^:]*):(.*)/) {
            print make "\t\t\tobj/$1.$2.o \\\n";
        }
    }
    print make "\n";
    print make "\t\${ARM_STRIP} --output-target=binary -o bin/$test.$type.bin obj/$test.$type.elf";
    print make "\n";
    print make "\n";
    print make "bin/$test.$type.mif: bin/$test.$type.bin\n";
    print make "\t\${BIN_TO_MIF} -f bin/$test.$type.bin -o bin/$test.$type.mif\n";
    print make "\t\${MIF_TO_CDL} -a 12 -f bin/$test.$type.mif -o bin/$test.$type.cdl\n";
    print make "\n";
    print make "bin/$test.$type.coe: bin/$test.$type.bin\n";
    print make "\t\${BIN_TO_MIF} -c -f bin/$test.$type.bin -o bin/$test.$type.coe\n";
    print make "\n";

}
print make " \n";

close( make );


#a Editor preferences and notes
# Local Variables: ***
# mode: perl ***
# outline-regexp: "#[a!]\\\|#[\t ]*[b-z][\t ]" ***
# End: ***

