#a Copyright
#  
#  This file 'Makefile' copyright Embisi Inc., 2004

#a Targets
all: simulation

.PHONY: simulation

simulation:
	(cd ../build; make sim)


#a Editor preferences and notes
# Local Variables: ***
# mode: Makefile ***
# outline-regexp: "#[a!]\\\|#[\t ]*[b-z][\t ]" ***
# End: ***

