#!/usr/bin/perl

#$tests = "--define prefetch_tests=1 ";
#$tests .= "--define system_scheduler_tests=1 ";
#$tests .= "--define system_ethernet_tests=1 ";
$tests .= "--define system_alu_tests=1 ";

$tnbt_cvs_root = $ENV{"TNBT_CVS_ROOT"};
$cwd = `pwd`;
chomp($cwd);

#chdir("$tnbt_cvs_root/hardware/design/repository/regressions/ethernet");
#chdir("$tnbt_cvs_root/hardware/design/repository/regressions/io");
#chdir("$tnbt_cvs_root/hardware/design/repository/regressions/postbus");
chdir("$tnbt_cvs_root/hardware/design/repository/regressions/gip");
#chdir("$tnbt_cvs_root/hardware/design/repository/regressions/ddr");
$sim = "$tnbt_cvs_root/hardware/design/build/simulation/linux/sim";
#$sim = $sim." --sl_debug_level 1 ";
#$sim = "valgrind --num-callers=8 ".$sim;
$sim = $sim." ".$tests;
print "$sim  --define run_dir=$cwd test.batch\n";
system("$sim  --define run_dir=$cwd test.batch");

